### ISSUE TITLE
한글 입력 오류 ( v1.8.7 )

### ISSUE THREAD

**Issue by HyeAnn-Lee** [falsy/delivery-tracker-for-whale#50]
안녕하세요,
이번 릴리즈에서 다음 영상과 같은 오류가 있는데 확인 부탁드립니다..!
영상과 관련된 스크린샷도 첨부합니다.
한글을 입력할 때, 타이핑되는 중간 과정이 모두 디스플레이되고 있습니다.

다른 사이드바 프로그램에서는 관찰되지 않는 현상이고, 1.8.6에서도 문제 없었던 것으로 기억합니다.

![image](https://github.com/user-attachments/assets/85fe2089-d2b7-47e1-a5c4-6f173ba2838a)

https://github.com/user-attachments/assets/57e85206-3914-4317-987f-3b32d3577340

**Comment by falsy** [comment]
@HyeAnn-Lee 인풋에 값 변경과 자동 저장 과정에서 지연이 발생해서 한글 입력에 문제가 있었던 것 같습니다.
항상 감사합니다 😭
